
all: clean
	pdflatex -shell-escape markov_chains
	pdflatex -shell-escape markov_chains
	pdflatex -shell-escape markov_chains
	pdflatex -shell-escape markov_chains

clean:
	rm -f *aux *bbl *log *blg *pdf *sta *dat *script *table
